class BibleBook {
  final String id;
  final String name;
  final int chapters;
  final bool isOldTestament;

  const BibleBook({
    required this.id,
    required this.name,
    required this.chapters,
    required this.isOldTestament,
  });
}

/// Catálogo canônico dos 66 livros da Bíblia, na ordem tradicional.
const List<BibleBook> bibleBooks = <BibleBook>[
  // Antigo Testamento
  BibleBook(id: 'gn', name: 'Gênesis', chapters: 50, isOldTestament: true),
  BibleBook(id: 'ex', name: 'Êxodo', chapters: 40, isOldTestament: true),
  BibleBook(id: 'lv', name: 'Levítico', chapters: 27, isOldTestament: true),
  BibleBook(id: 'nm', name: 'Números', chapters: 36, isOldTestament: true),
  BibleBook(id: 'dt', name: 'Deuteronômio', chapters: 34, isOldTestament: true),
  BibleBook(id: 'js', name: 'Josué', chapters: 24, isOldTestament: true),
  BibleBook(id: 'jud', name: 'Juízes', chapters: 21, isOldTestament: true),
  BibleBook(id: 'rt', name: 'Rute', chapters: 4, isOldTestament: true),
  BibleBook(id: '1sm', name: '1 Samuel', chapters: 31, isOldTestament: true),
  BibleBook(id: '2sm', name: '2 Samuel', chapters: 24, isOldTestament: true),
  BibleBook(id: '1kgs', name: '1 Reis', chapters: 22, isOldTestament: true),
  BibleBook(id: '2kgs', name: '2 Reis', chapters: 25, isOldTestament: true),
  BibleBook(id: '1ch', name: '1 Crônicas', chapters: 29, isOldTestament: true),
  BibleBook(id: '2ch', name: '2 Crônicas', chapters: 36, isOldTestament: true),
  BibleBook(id: 'ezr', name: 'Esdras', chapters: 10, isOldTestament: true),
  BibleBook(id: 'ne', name: 'Neemias', chapters: 13, isOldTestament: true),
  BibleBook(id: 'et', name: 'Ester', chapters: 10, isOldTestament: true),
  BibleBook(id: 'job', name: 'Jó', chapters: 42, isOldTestament: true),
  BibleBook(id: 'ps', name: 'Salmos', chapters: 150, isOldTestament: true),
  BibleBook(id: 'prv', name: 'Provérbios', chapters: 31, isOldTestament: true),
  BibleBook(id: 'ec', name: 'Eclesiastes', chapters: 12, isOldTestament: true),
  BibleBook(id: 'so', name: 'Cânticos', chapters: 8, isOldTestament: true),
  BibleBook(id: 'is', name: 'Isaías', chapters: 66, isOldTestament: true),
  BibleBook(id: 'jr', name: 'Jeremias', chapters: 52, isOldTestament: true),
  BibleBook(id: 'lm', name: 'Lamentações de Jeremias', chapters: 5, isOldTestament: true),
  BibleBook(id: 'ez', name: 'Ezequiel', chapters: 48, isOldTestament: true),
  BibleBook(id: 'dn', name: 'Daniel', chapters: 12, isOldTestament: true),
  BibleBook(id: 'ho', name: 'Oséias', chapters: 14, isOldTestament: true),
  BibleBook(id: 'jl', name: 'Joel', chapters: 3, isOldTestament: true),
  BibleBook(id: 'am', name: 'Amós', chapters: 9, isOldTestament: true),
  BibleBook(id: 'ob', name: 'Obadias', chapters: 1, isOldTestament: true),
  BibleBook(id: 'jn', name: 'Jonas', chapters: 4, isOldTestament: true),
  BibleBook(id: 'mi', name: 'Miquéias', chapters: 7, isOldTestament: true),
  BibleBook(id: 'na', name: 'Naum', chapters: 3, isOldTestament: true),
  BibleBook(id: 'hk', name: 'Habacuque', chapters: 3, isOldTestament: true),
  BibleBook(id: 'zp', name: 'Sofonias', chapters: 3, isOldTestament: true),
  BibleBook(id: 'hg', name: 'Ageu', chapters: 2, isOldTestament: true),
  BibleBook(id: 'zc', name: 'Zacarias', chapters: 14, isOldTestament: true),
  BibleBook(id: 'ml', name: 'Malaquias', chapters: 4, isOldTestament: true),
  // Novo Testamento
  BibleBook(id: 'mt', name: 'Mateus', chapters: 28, isOldTestament: false),
  BibleBook(id: 'mk', name: 'Marcos', chapters: 16, isOldTestament: false),
  BibleBook(id: 'lk', name: 'Lucas', chapters: 24, isOldTestament: false),
  BibleBook(id: 'jo', name: 'João', chapters: 21, isOldTestament: false),
  BibleBook(id: 'act', name: 'Atos', chapters: 28, isOldTestament: false),
  BibleBook(id: 'rm', name: 'Romanos', chapters: 16, isOldTestament: false),
  BibleBook(id: '1co', name: '1 Coríntios', chapters: 16, isOldTestament: false),
  BibleBook(id: '2co', name: '2 Coríntios', chapters: 13, isOldTestament: false),
  BibleBook(id: 'gl', name: 'Gálatas', chapters: 6, isOldTestament: false),
  BibleBook(id: 'eph', name: 'Efésios', chapters: 6, isOldTestament: false),
  BibleBook(id: 'ph', name: 'Filipenses', chapters: 4, isOldTestament: false),
  BibleBook(id: 'cl', name: 'Colossenses', chapters: 4, isOldTestament: false),
  BibleBook(id: '1ts', name: '1 Tessalonicenses', chapters: 5, isOldTestament: false),
  BibleBook(id: '2ts', name: '2 Tessalonicenses', chapters: 3, isOldTestament: false),
  BibleBook(id: '1tm', name: '1 Timóteo', chapters: 6, isOldTestament: false),
  BibleBook(id: '2tm', name: '2 Timóteo', chapters: 4, isOldTestament: false),
  BibleBook(id: 'tt', name: 'Tito', chapters: 3, isOldTestament: false),
  BibleBook(id: 'phm', name: 'Filemom', chapters: 1, isOldTestament: false),
  BibleBook(id: 'hb', name: 'Hebreus', chapters: 13, isOldTestament: false),
  BibleBook(id: 'jm', name: 'Tiago', chapters: 5, isOldTestament: false),
  BibleBook(id: '1pe', name: '1 Pedro', chapters: 5, isOldTestament: false),
  BibleBook(id: '2pe', name: '2 Pedro', chapters: 3, isOldTestament: false),
  BibleBook(id: '1jo', name: '1 João', chapters: 5, isOldTestament: false),
  BibleBook(id: '2jo', name: '2 João', chapters: 1, isOldTestament: false),
  BibleBook(id: '3jo', name: '3 João', chapters: 1, isOldTestament: false),
  BibleBook(id: 'jd', name: 'Judas', chapters: 1, isOldTestament: false),
  BibleBook(id: 're', name: 'Apocalipse', chapters: 22, isOldTestament: false),
];
